-- AlterTable
ALTER TABLE "MoneyReceipt" ADD COLUMN "tdsPct" REAL NOT NULL DEFAULT 0;
ALTER TABLE "MoneyReceipt" ADD COLUMN "tdsAmt" REAL NOT NULL DEFAULT 0;
ALTER TABLE "MoneyReceipt" ADD COLUMN "paidAmt" REAL NOT NULL DEFAULT 0;
ALTER TABLE "MoneyReceipt" ADD COLUMN "otherDed" REAL NOT NULL DEFAULT 0;
