-- AlterTable
ALTER TABLE "Maintenance" ADD COLUMN IF NOT EXISTS "diesel" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Maintenance" ADD COLUMN IF NOT EXISTS "otherExpenses" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Maintenance" ADD COLUMN IF NOT EXISTS "fasTag" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Maintenance" ADD COLUMN IF NOT EXISTS "freight" DOUBLE PRECISION NOT NULL DEFAULT 0;
