-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "passwordOtpHash" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "passwordOtpExpires" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "passwordOtpAttempts" INTEGER NOT NULL DEFAULT 0;
