-- AlterTable
ALTER TABLE "Bill" ADD COLUMN "source" TEXT NOT NULL DEFAULT 'DPR';

-- AlterTable
ALTER TABLE "BookingSlip" ADD COLUMN "lorryNo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "BookingSlip" ADD COLUMN "receiptDate" TEXT NOT NULL DEFAULT '';
ALTER TABLE "BookingSlip" ADD COLUMN "guaranteeWeight" TEXT NOT NULL DEFAULT '';
ALTER TABLE "BookingSlip" ADD COLUMN "freight" REAL NOT NULL DEFAULT 0;
ALTER TABLE "BookingSlip" ADD COLUMN "advance" REAL NOT NULL DEFAULT 0;
ALTER TABLE "BookingSlip" ADD COLUMN "balance" REAL NOT NULL DEFAULT 0;
ALTER TABLE "BookingSlip" ADD COLUMN "receiptNo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "BookingSlip" ADD COLUMN "remark" TEXT NOT NULL DEFAULT '';
ALTER TABLE "BookingSlip" ADD COLUMN "mailId" TEXT NOT NULL DEFAULT '';
