-- AlterTable
ALTER TABLE "LrBooking" ADD COLUMN IF NOT EXISTS "cgstAmt" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "LrBooking" ADD COLUMN IF NOT EXISTS "sgstAmt" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "LrBooking" ADD COLUMN IF NOT EXISTS "igstAmt" DOUBLE PRECISION NOT NULL DEFAULT 0;
