-- AlterTable
ALTER TABLE "Maintenance" ADD COLUMN IF NOT EXISTS "adBlue" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Maintenance" ADD COLUMN IF NOT EXISTS "maintenanceCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
